//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfMap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтверждение.
        /// </summary>
        public static string ConfirmationCaption {
            get {
                return ResourceManager.GetString("ConfirmationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Создание новых точек.
        /// </summary>
        public static string CreateNewHeader {
            get {
                return ResourceManager.GetString("CreateNewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите удалить текущую точку?.
        /// </summary>
        public static string DeleteConfirmationText {
            get {
                return ResourceManager.GetString("DeleteConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Удалить текущую точку.
        /// </summary>
        public static string DeletePointHeader {
            get {
                return ResourceManager.GetString("DeletePointHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Редактирование.
        /// </summary>
        public static string EditHeader {
            get {
                return ResourceManager.GetString("EditHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Режим редактирования.
        /// </summary>
        public static string EditModeHeader {
            get {
                return ResourceManager.GetString("EditModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Программа не смогла загрузить базу с точками.
        /// </summary>
        public static string ErrorOnLoad {
            get {
                return ResourceManager.GetString("ErrorOnLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверены, что хотите выйти?.
        /// </summary>
        public static string ExitConfirmationText {
            get {
                return ResourceManager.GetString("ExitConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В_ыход.
        /// </summary>
        public static string ExitHeader {
            get {
                return ResourceManager.GetString("ExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П_рограмма.
        /// </summary>
        public static string FileHeader {
            get {
                return ResourceManager.GetString("FileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to П_олноэкранный режим.
        /// </summary>
        public static string FullScreenHeader {
            get {
                return ResourceManager.GetString("FullScreenHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Перемещение текущей точки.
        /// </summary>
        public static string MovePointHeader {
            get {
                return ResourceManager.GetString("MovePointHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите описание точки.
        /// </summary>
        public static string NewPointDefaultDescription {
            get {
                return ResourceManager.GetString("NewPointDefaultDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите название точки.
        /// </summary>
        public static string NewPointDefaultName {
            get {
                return ResourceManager.GetString("NewPointDefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Сохранить всё.
        /// </summary>
        public static string SaveHeader {
            get {
                return ResourceManager.GetString("SaveHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внимание! 
        ///У вас остались несохраненные правки..
        /// </summary>
        public static string UnsavedEditsConfirmationText {
            get {
                return ResourceManager.GetString("UnsavedEditsConfirmationText", resourceCulture);
            }
        }
    }
}
